# Week3 Assignment Solution

## Imports

In [199]:
import math
import random
from functools import reduce
from functools import partial
import re
import numpy as np
from math import exp
import string

## Q1. Write a function using only list filter lambda that can tell whether a number is a Fibonacci number or not. You can use a pre-calculated list/dict to store fab numbers till 10000

In [122]:
# Generate a pre-computed fibonnaci series
def generate_fib(n):
    fib_series = [0, 1]
    
    for _ in range(n-2):
        fib_series.append(reduce(lambda x,y:x+y, fib_series[-2:]))
    if n>1:
        return fib_series
    else:
        return fib_series[:n]

In [123]:
fib_list = generate_fib(10000)
fib_list[:10]

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

In [124]:
fn = lambda x:True if x in fib_list else False

In [125]:
fn(4), fn(8)

(False, True)

## Q2. Using list comprehension (and zip/lambda/etc if required) write five different expressions that:

### 2.1. Add 2 iterables a and b such that a is even and b is odd

In [119]:
#Creating two list
l1 = list(range(0, 50, 2))
l2 = list(range(0, 50, 5))
print(f"List 1>>>> {l1}")
print(f"List 2>>>> {l2}")

List 1>>>> [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]
List 2>>>> [0, 5, 10, 15, 20, 25, 30, 35, 40, 45]


In [120]:
#Adding two list using zip
print(f"Sum of two list >>>> {[a+b for a,b in zip(l1, l2) if a%2 ==0 and b%2 != 0]}")

Sum of two list >>>> [7, 21, 35, 49, 63]


### 2.2. Strips every vowel from a string provided (tsai>>t s)

In [97]:
# Lambda function to remove vowels from a string and return a list
vowel_strip = lambda input_str: [x for x in input_str if x not in ['a', 'e', 'i', 'o', 'u']]

# Reduce to add the contents of the list and returns a string
reduce(lambda x,y: x+y , vowel_strip("tsai"))

'ts'

### 2.3. Acts like a ReLU function for a 1D array

In [134]:
# Generating the 1-D array
one_d_array = np.array([random.randint(-10, 10) for _ in range(20)])
one_d_array

array([  5,   1,  -4,  -1,   1,   3, -10,  -4,   1,  -9,   5,  -6,  -2,
        -5,  -1,  -8,  -8,  -9,  -7,   2])

In [140]:
# List comprehension to take a list and return a list that acts like it has passed through ReLU
np.array([0 if x<=0 else x for x in one_d_array])

array([5, 1, 0, 0, 1, 3, 0, 0, 1, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 2])

### 2.4. Acts like a sigmoid function for a 1D array

In [139]:
# List comprehension to take a list and return a list that acts like it has passed through Sigmoid
np.array([1/(1+exp(-x)) for x in one_d_array])

array([9.93307149e-01, 7.31058579e-01, 1.79862100e-02, 2.68941421e-01,
       7.31058579e-01, 9.52574127e-01, 4.53978687e-05, 1.79862100e-02,
       7.31058579e-01, 1.23394576e-04, 9.93307149e-01, 2.47262316e-03,
       1.19202922e-01, 6.69285092e-03, 2.68941421e-01, 3.35350130e-04,
       3.35350130e-04, 1.23394576e-04, 9.11051194e-04, 8.80797078e-01])

### 2.5. Takes a small character string and shifts all characters by 5 (handle boundary conditions) tsai>>yxfn

In [145]:
str2 = "tsai"
print(reduce(lambda x,y : x+y , [chr(ord(ch)+5) if ord(ch) < 118 else chr((ord(ch)+5)%122+96) for ch in str2]))

#Checking boundary conditions
str2 = "xyza"
print(reduce(lambda x,y : x+y , [chr(ord(ch)+5) if ord(ch) < 118 else chr((ord(ch)+5)%122+96) for ch in str2]))

yxfn
cdef


## Q3. A list comprehension expression that takes a ~200 word paragraph (write your own paragraph to check), and checks whether it has any of the swear words mentioned in https://github.com/RobertJGabriel/Google-profanity-words/blob/master/list.txt

In [149]:
#
text = """
Call me Ishmael. Some years ago - never mind how long precisely - having little or no money in my purse, and nothing particular
to interest me on shore, I thought I would sail about a little and see the watery part of the world. It is a way I have of 
driving off the spleen and regulating the circulation. Whenever I find myself growing grim about the mouth; whenever it is a 
damp, drizzly November in my soul; whenever I find myself involuntarily pausing before coffin warehouses, and bringing up the 
rear of every funeral I meet; and especially whenever my hypos get such an upper hand of me, that it requires a strong moral 
principle to prevent me from deliberately stepping into the street, and methodically knocking people's hats off - then, I 
account it high time to get to sea as soon as I can. This is my substitute for pistol and ball. With a philosophical flourish 
Cato throws himself upon his sword; I quietly take to the ship. There is nothing surprising in this. If they but knew it, 
almost all men in their degree, some time or other, cherish very nearly the same feelings towards the ocean with me.
"""

In [152]:
with open('Google_Profanity_Words.txt') as f:
    profanity = [line.rstrip().lower() for line in f]

In [174]:
"No Profanity" if len([word for word in re.split("[\\s.,!?:;'\"-]+",text.lower()) if word in profanity]) == 0 else "Profanity"

'No Profanity'

## Q4. Using reduce functions

### 4.1 Add only even numbers in a list

In [184]:
# Generate List
l1 = list(range(0, 100, 5))

# Calculate Sum for even numbers in the list
reduce(lambda x,y: x+y if y%2==0 else x, l1)

450

### 4.2 Find the biggest character in a string (printable ascii characters)

In [185]:
#Defining the string
biggest_char = "Abc xyz 123 ;"

#Get the largest Ascii character
reduce(lambda x,y: x if ord(x)>ord(y) else y, biggest_char)

'z'

### 4.3 Adds every 3rd number in a list

In [195]:
li = list(range(0, 100, 6))
print(f"Generated List >>> {li}")

# Sum of every third element in the list
print(f"Sum of every third element in the above list >>> {reduce(lambda x,y: x+y, [i for idx, i in enumerate(li) if idx%3 == 0])}")

Generated List >>> [0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96]
Sum of every third element in the above list >>> 270


In [196]:
[i for idx, i in enumerate(li) if idx%2 == 0]

[0, 12, 24, 36, 48, 60, 72, 84, 96]

## Q5. Using randint, random.choice and list comprehensions, write an expression that generates 15 random KADDAADDDD number plates, where KA is fixed, D stands for a digit, and A stands for Capital alphabets. 10<<DD<<99 & 1000<<DDDD<<9999

In [206]:
random.seed(0)
[f"KA{random.randint(10, 99)}{random.choice(string.ascii_uppercase)}{random.choice(string.ascii_uppercase)}\
{random.randint(1000, 9999)}" for _ in range(15)]

['KA59YN1663',
 'KA43QP7634',
 'KA48PL4578',
 'KA74EJ3289',
 'KA22TZ5104',
 'KA78WZ3407',
 'KA49DX2208',
 'KA97KP2649',
 'KA55NK4350',
 'KA80PO9541',
 'KA43BZ9989',
 'KA11CX7534',
 'KA95UA9086',
 'KA52HX6328',
 'KA18GS4632']

## Q6. Write the above again from scratch where KA can be changed to DL, and 1000/9999 ranges can be provided.

In [226]:
def num_plate(state_name, digits_range_start, digits_range_end, n_plates, random_state = 0):
    """Generates number plates
    Inputs:
        state_name: str
            Two char string for the state
        digits_range_start: int
            Start of range for last four digits of number plate between 1000 to 9999
        digits_range_start: int
            End of range for last four digits of number plate between 1000 to 9999
        n_plates: number of number plates to be generated
    Returns:
        num_plate: List of number plate with number in KADDAADDDD format, D stands for a digit, and A stands for Capital alphabets"""
    
    if not isinstance(state_name, str):
        raise TypeError(f"State can be only two char String")
    if not isinstance(digits_range_start,int):
        raise TypeError(f"Last four digits should be between 1000 and 9999")
    if not isinstance(digits_range_end,int):
        raise TypeError(f"Last four digits should be between 1000 and 9999")
    if not isinstance(random_state,int):
        raise TypeError(f"Random State has to be an integer")
    if not state_name:
        raise ValueError(f"State can't be null")
    
    random.seed(random_state)

    num_plate = [fr"{state_name}{random.randint(10, 99)}{random.choice(string.ascii_uppercase)}{random.choice(string.ascii_uppercase)}{random.randint(digits_range_start,digits_range_end)}" for _ in range(n_plates)]

    return(num_plate)

In [227]:
num_plate("DL", 1500, 2500, 15)

['DL59YN1541',
 'DL43QP1914',
 'DL48PL2097',
 'DL37QE1788',
 'DL27YD2133',
 'DL42RW2329',
 'DL87EJ1601',
 'DL19VK1983',
 'DL81DL1944',
 'DL50TU2434',
 'DL36RP1953',
 'DL76IB2324',
 'DL80AC2236',
 'DL61WZ2184',
 'DL90AT2005']